version: 2

models:
  - name: olist_products_seller
    description: "Modelo com informações sobre os vendedores de produtos."
    columns:
      - name: product_id
        description: "ID único do produto"
        tests:
          - unique: {}   # Verifica se os valores da coluna são únicos
          - not_null: {} # Verifica se não há valores nulos
      
      - name: product_category_name
        description: "Nome da categoria do produto"
        tests:
          - unique: {}   # Verifica se os valores da coluna são únicos
          - not_null: {} # Verifica se não há valores nulos
          

